name = "Newb §6Pineapple §a[Revived]§r"
version = [0, 1, 0]
min_supported_mc_version = [1, 21, 130]
description = '''
%v - §c%w§r
§7Another newb variants to improve your minecraft visual with bright lighting, low saturation, soft shadow, foggy environment and immersive bloom.§r
''' # %w = patch warning, %v = version
authors = ["ethereal", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "95f774cf-4afa-73e7-a21a-72146307b1d2" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]

[info] 
copyright = '''
Copyright © 2025 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

[label]
text = '''
§cShaders are not officially supported on Minecraft Bedrock.
Some devices will experience rounded cloud bugs§r

Configuration Settings: 
Recommended set in-game brightness to 20
Lower render view distance (8-10) for better fog experience
Don't use experimental features and education mode (or some bugs will occur)

Thank you very much for downloading and using this shader :)§r
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "REALISTIC_CLOUDS"
materials = ["Clouds"]
description = '''
Realistic Clouds
'''

[[subpack]]
define = "BOX_CLOUDS"
materials = ["Clouds"]
description = '''
Box Clouds
'''

[[subpack]]
define = "SIMPLE_CLOUDS"
materials = ["Clouds"]
description = '''
Simple Clouds
'''

[[subpack]]
define = "NO_WAVE_NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog and wave effects
'''

[[subpack]]
define = "NO_FOG"
materials = ["RenderChunk"]
description = '''
No fog effect
'''

[[subpack]]
define = "NO_WAVE"
materials = ["RenderChunk"]
description = '''
No wave effects
'''

#[[subpack]]
#define = "LITE"
#materials = ["Sky", "RenderChunk", "Actor", "ActorGlint", "EndSky", "Clouds", "SunMoon", "Weather", "ItemInHandTextured", "ItemInHandColor", "ItemInHandColorGlint", "Stars"]
#description = '''
#Many effects disabled. A bit lighter!
#'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
